services:
  lmlab:
    image: lmlab:latest
    container_name: lmlab
    restart: unless-stopped
    ports:
      - "8484:8484"
    volumes:
      - /srv/sparv/:/app/sparv/:ro
    environment: #NOTE: see README.md for full details, here's an example:
      LMLAB_IDLE_TIMEOUT: 30
